### ISSUE TITLE
KeyRingInfo.getPrimaryKeyExpirationDate() == "No suitable signatures found on the key."

### ISSUE THREAD

**Issue by DenBond7** [pgpainless/pgpainless#158] opened 2021-07-21 11:54 UTC
@vanitasvitae I have the following key

[OpenPGP_0x3970E032989458B8.txt](https://github.com/pgpainless/pgpainless/files/6855302/OpenPGP_0x3970E032989458B8.txt)

When I try to use the following code

```kotlin
val keyRingInfo = KeyRingInfo(this)
...
return PgpKeyDetails(
    isFullyDecrypted = keyRingInfo.isFullyDecrypted,
    isFullyEncrypted = keyRingInfo.isFullyEncrypted,
    privateKey = privateKey,
    publicKey = publicKey,
    users = keyRingInfo.userIds,
    ids = keyIdList,
    created = keyRingInfo.creationDate.time,
    lastModified = keyRingInfo.lastModified?.time,
    expiration = keyRingInfo.primaryKeyExpirationDate?.time,
    algo = algo
  )
```
I receive `NoSuchElementException("No suitable signatures found on the key.")` for `keyRingInfo.primaryKeyExpirationDate?.time`

What is strange for me?

In the library, we see the following

```java
    /**
     * Return the date of expiration of the primary key or null if the key has no expiration date.
     *
     * @return expiration date
     */
    public @Nullable Date getPrimaryKeyExpirationDate() {
        PGPSignature primaryUserIdCertification = getLatestUserIdCertification(getPrimaryUserId());
        if (primaryUserIdCertification != null) {
            return SignatureSubpacketsUtil.getKeyExpirationTimeAsDate(primaryUserIdCertification, getPublicKey());
        }

        PGPSignature directKeySig = getLatestDirectKeySelfSignature();
        if (directKeySig != null) {
            return SignatureSubpacketsUtil.getKeyExpirationTimeAsDate(directKeySig, getPublicKey());
        }
        throw new NoSuchElementException("No suitable signatures found on the key.");
    }

```

It confuses me a little. Because I thought that if the library can't recognize a date I should receive `null`

The second interesting thing. OpenPGP.js show the following info

```
(1) Primary keys found: 1  
(2) ----- Testing key 0 -----  
(3) PK 0 > Key type: openpgp  
(4) PK 0 > Is Private?: [-] false  
(5) PK 0 > User id 0: hidden <hidden>  
(6) PK 0 > Primary User: hidden <hidden>  
(7) PK 0 > Fingerprint: 3E29 11CD 6ED6 A8B3 E223 7C3A 3970 E032 9894 58B8  
(8) PK 0 > Subkeys: [-] 1  
(9) PK 0 > Primary key algo: [-] rsa_encrypt_sign  
(10) PK 0 > Usage flags: [-] [sign_data, certify_keys]  
(11) PK 0 > Primary key verify: [-] valid  
(12) PK 0 > Primary key creation?: [-] 1397231447 or 2014-04-11T15:50:47.000Z  
(13) PK 0 > Primary key expiration?: [-] 1649607353 or 2022-04-10T16:15:53.000Z  
(14) PK 0 > Encrypt/Decrypt test: Encryption with key was successful:   
(15) PK 0 > Encrypt/Decrypt test: Got error performing encryption/decryption test: Error: Cannot check encryption status of secret keys in a Public Key:   
(16) PK 0 > SK 0 > LongId: [-] 9D45B41A17DBA5E9  
(17) PK 0 > SK 0 > Created: [-] 1397231447 or 2014-04-11T15:50:47.000Z  
(18) PK 0 > SK 0 > Algo: [-] rsa_encrypt_sign  
(19) PK 0 > SK 0 > Usage flags: [-] [encrypt_communication, encrypt_storage]  
(20) PK 0 > SK 0 > Verify: [-] OK  
(21) PK 0 > SK 0 > Subkey tag: [-] 14  
(22) PK 0 > SK 0 > Subkey getBitSize: [-] 4096  
(23) PK 0 > SK 0 > Subkey decrypted: [-] null  
(24) PK 0 > SK 0 > Binding signature length: [-] 1  
(25) PK 0 > SK 0 > SIG 0 > Key flags: [-] 12  
(26) PK 0 > SK 0 > SIG 0 > Tag: [-] 2  
(27) PK 0 > SK 0 > SIG 0 > Version: [-] 4  
(28) PK 0 > SK 0 > SIG 0 > Public key algorithm: [-] 1  
(29) PK 0 > SK 0 > SIG 0 > Sig creation time: [-] 1523463377 or 2018-04-11T16:16:17.000Z  
(30) PK 0 > SK 0 > SIG 0 > Sig expiration time: [-] 1397231447 + 252375930 seconds, which is: 1649607377 or 2022-04-10T16:16:17.000Z  
(31) PK 0 > SK 0 > SIG 0 > Verified: [-] true  
(32) PK 0 > expiration: [-] 1649607353000  
(33) PK 0 > internal dateBeforeExpiration: [-] undefined  
(34) PK 0 > internal usableForEncryptionButExpired: [-] false  
(35) PK 0 > internal usableForSigningButExpired: [-] false  
```

**(13) PK 0 > Primary key expiration?: [-] 1649607353 or 2022-04-10T16:15:53.000Z** 

Could you check my example?

**Comment by vanitasvitae** [comment] 2021-07-21 12:13
Ah, I think I know what the issue probably is. I'd suspect that the user-id signature is not taken into consideration, as it is not marked as primary userid? Still, PGPainless should know how to deal with that situation, so its clearly a bug in PGPainless (given that this really is the cause).

I will create a test case later to reproduce and fix the issue.

**Comment by vanitasvitae** [comment] 2021-07-21 18:23
I did some tinkering:

Apparently the first signature that gets checked is the one created at `2014-04-11 15:50:47 UTC`. This signature gets rejected, as it uses SHA-1, which is being rejected by the default SignatureHashAlgorithmPolicy (you may want to change that if it better suits your needs, see the `Policy` class, or the [ManagePolicy](https://github.com/pgpainless/pgpainless/blob/master/pgpainless-core/src/test/java/org/pgpainless/example/ManagePolicy.java#L93) example test).

The next signature that is checked (the one created at `2018-03-05 14:55:58 UTC`, while using an acceptable hash algorithm (SHA-256) appears to be incorrect (BCs `signature.verifyCertification(userId, certifiedKey)` returns false). So this signature too is being rejected.

Lastly, the latest signature (created at `2018-04-11 16:15:53 UTC` once again uses SHA-1 as signature hash algorithm, so its being rejected by the default hash algorithm policy.

Since there is no acceptable signature, PGPainless cannot determine the keys expiration date. Returning `null` here would cause confusion, since null means *explicitly no expiry*, while in this case we simply don't know when the key expires.

I wonder why the SHA-256 signature fails to verify, I will check that next. It would be interesting to know, if other implementations also reject that signature and for what exact reason.

Setting a custom hash algorithm policy that accepts SHA-1 yields the expected result.

**Comment by DenBond7** [comment] 2021-07-22 07:01
Thank you for the investigation!

> Since there is no acceptable signature, PGPainless cannot determine the keys expiration date. Returning null here would cause confusion, since null means explicitly no expiry, while in this case we simply don't know when the key expires.

Agree. Throw an exception it's a good choice to prevent confusion. It would be nice to update `docs` to make it clear(an exception will be thrown if we can't define that value).

> I wonder why the SHA-256 signature fails to verify, I will check that next. It would be interesting to know, if other implementations also reject that signature and for what exact reason.

I'm looking forward for results

> This signature gets rejected, as it uses SHA-1, which is being rejected by the default SignatureHashAlgorithmPolicy (you may want to change that if it better suits your needs, see the Policy class, or the ManagePolicy example test).

@tomholub What do you think about it? Can it be a solution for us?

**Comment by tomholub** [comment] 2021-07-22 09:20
SHA-1 is ignored correctly. However, it would be good to look into why exactly this happens:

> The next signature that is checked (the one created at 2018-03-05 14:55:58 UTC, while using an acceptable hash algorithm (SHA-256) appears to be incorrect (BCs signature.verifyCertification(userId, certifiedKey) returns false). So this signature too is being rejected.

**Comment by tomholub** [comment] 2021-07-22 10:14
Interesting to note is the difference in how OpenPGP.js interprets it. It shows two signatures:

![image](https://user-images.githubusercontent.com/6306961/126623769-654413fa-0c72-4d59-8696-8d4fa14a5fb6.png)

first

![image](https://user-images.githubusercontent.com/6306961/126623828-431922c8-1db3-461c-acb1-814cb50d0cb6.png)

second

![image](https://user-images.githubusercontent.com/6306961/126623894-946a9efc-8e8b-4e08-9d67-67faaabc7b23.png)

**Comment by tomholub** [comment] 2021-07-22 10:18
So OpenPGP.js probably also thought that the SHA-256  from `2018-03-05 14:55:58 UTC` is invalid - therefore, nothing to see there.

Rejecting SHA-1 is correct either way.

I think PGPainless is behaving correctly here, so I'm inclined to close this unless @vanitasvitae also stumbled into some actionable item while debugging this.

**Comment by vanitasvitae** [comment] 2021-07-22 10:20
I'd still like to know why that sig is broken. Do you happen to know what implementation made it?

**Comment by tomholub** [comment] 2021-07-22 10:24
:shrug: but I'd also be interested to know exactly why it's broken

The public key was sent to us with Thunderbird 78.7.1 so I guess that suggests gnupg? (unless this is a recent version that uses OpenPGP.js?)

**Comment by vanitasvitae** [comment] 2021-07-22 12:02
I found out why the sig appears incorrect...
Its made by a different key :D :man_facepalming: 

Now I need to find out, why PGPainless was trying to verify the sig using the primary key.

**Closed as completed by vanitasvitae** 2021-07-22 12:02 UTC
Labels: bug, module: core

**Comment by vanitasvitae** [comment] 2021-07-22 12:24
I added a check for non-self-signatures to the user-id certification self-signature picker method.
