### ISSUE TITLE
Expiration date for a particular purpose?

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#122] opened 2021-05-22 12:49 UTC
Could there be a combined method? OpenPGP.js has methods for `getExpirationDate(use=ANY)`, `getExpirationDate(use=SIGNING)`, `getExpirationDate(use=ENCRYPTION)`.

Then it will evaluate combination of primary and subkeys holistically to figure out if the key can be used for that purpose as a whole. This would be very helpful for us.

_Originally posted by @tomholub in https://github.com/pgpainless/pgpainless/issues/113#issuecomment-832536082_

**Comment by vanitasvitae** [comment] 2021-05-22 12:54
Sure, although I'd probably name it `ENCRYPTION_AND_SIGNING`, since there are other uses such as `AUTHENTICATION`, which are probably unrelated to your use-case, but using `ANY` would still be misleading in that case.

Duplicate of #114

**Closed as completed by vanitasvitae** 2021-05-22 12:54 UTC

**Comment by tomholub** [comment] 2021-05-22 13:00
Sorry, I managed to overlook the earlier issue :-)
