### ISSUE TITLE
Trying to revoke key, getting java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#53] opened 2021-01-19 08:49 UTC
Here is code example
https://gist.github.com/IvanPizhenko/02873badbedf286d39e749aa3147984c
(see included pom.xml for library versions)

Running on the Ubuntu 20.04 LTS with latest OpenJDK 11 from the standard Ubuntu repositories.

It gets me an exception:
```
/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -javaagent:/home/ivan/Programs/idea/lib/idea_rt.jar=38631:/home/ivan/Programs/idea/bin -Dfile.encoding=UTF-8 -classpath /home/ivan/pro/misc/eclipse-workspace/mysample/target/classes:/home/ivan/.m2/repository/org/pgpainless/pgpainless-core/0.2.0-alpha5/pgpainless-core-0.2.0-alpha5.jar:/home/ivan/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.68/bcprov-jdk15on-1.68.jar:/home/ivan/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/ivan/.m2/repository/org/bouncycastle/bcpg-jdk15on/1.68/bcpg-jdk15on-1.68.jar mysample.PgpainlessRevokeKeyFailureDemo
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.pgpainless.key.util.SignatureUtils.negotiateHashAlgorithm(SignatureUtils.java:48)
	at org.pgpainless.key.util.SignatureUtils.getPgpContentSignerBuilderForKey(SignatureUtils.java:40)
	at org.pgpainless.key.util.SignatureUtils.getSignatureGeneratorFor(SignatureUtils.java:34)
	at org.pgpainless.key.util.SignatureUtils.getSignatureGeneratorFor(SignatureUtils.java:29)
	at org.pgpainless.key.modification.secretkeyring.SecretKeyRingEditor.generateRevocation(SecretKeyRingEditor.java:387)
	at org.pgpainless.key.modification.secretkeyring.SecretKeyRingEditor.revokeSubKey(SecretKeyRingEditor.java:373)
	at org.pgpainless.key.modification.secretkeyring.SecretKeyRingEditor.revokeSubKey(SecretKeyRingEditor.java:286)
	at org.pgpainless.key.modification.secretkeyring.SecretKeyRingEditor.revoke(SecretKeyRingEditor.java:265)
	at org.pgpainless.key.modification.secretkeyring.SecretKeyRingEditorInterface.revoke(SecretKeyRingEditorInterface.java:127)
	at mysample.PgpainlessRevokeKeyFailureDemo.revokeKey(PgpainlessRevokeKeyFailureDemo.java:68)
	at mysample.PgpainlessRevokeKeyFailureDemo.main(PgpainlessRevokeKeyFailureDemo.java:49)

Process finished with exit code 1
```

**Comment by vanitasvitae** [comment] 2021-01-19 10:47
I will have a look at this. Thanks for the report!

**Comment by vanitasvitae** [comment] 2021-01-19 14:37
The problem was caused by PGPainless not handling key signatures correctly, if the signature is of type 0x10 (generic certification, see https://tools.ietf.org/html/rfc4880#section-5.2.1).

Basically I overlooked the statement
>      Most OpenPGP implementations make their "key signatures" as 0x10
>      certifications.  Some implementations can issue 0x11-0x13
>      certifications, but few differentiate between the types.

This has now been fixed and revoking the key works now :)
The fix will be included in the next release.

Thanks for the report!

**Closed as completed** 2021-01-19 14:38 UTC

**Comment by tomholub** [comment] 2021-01-19 15:18
Thank you for looking into it - that would suggest that PGPainless itself is using signatures other than 0x10? Which one is it using?

If 0x10 is indeed the most common, it may be worthwhile to consider using 0x10 for pgpainless-generated signatures, for maximum possible compatibility. (my imagination - unsure if it makes a real difference)

**Comment by IvanPizhenko** [comment] 2021-01-19 15:22
thanks @vanitasvitae! when the new release is expected?

**Comment by vanitasvitae** [comment] 2021-01-19 15:44
> that would suggest that PGPainless itself is using signatures other than 0x10? Which one is it using?

PGPainless is currently creating signatures of type 0x13 as I expected key signatures to be too ciritcal to be "generic".
The formulation in the RFC made me be suspicious of 0x10 signatures:

> 0x10: Generic certification of a User ID and Public-Key packet.
>       The issuer of this certification does not make any particular
>       assertion as to how well the certifier has checked that the owner
>       of the key is in fact the person described by the User ID.

But I agree that it might make sense to switch to 0x10 signatures. I will research into this.

> when the new release is expected?

I have not planned a particular release date, but I'm quite flexible, so if there is demand, I can try to make a new release later today.
That would be a good opportunity to test the new support for setting key expiration dates :)

**Comment by IvanPizhenko** [comment] 2021-01-19 16:00
> I have not planned a particular release date, but I'm quite flexible, so if there is demand, I can try to make a new release later today.

That would be nice, will appreciate that!

> That would be a good opportunity to test the new support for setting key expiration dates :)

Can't promise, but I think at some point we will do it.

**Comment by IvanPizhenko** [comment] 2021-01-19 22:55
Looked at #48. At the moment we have that code commented out, but since #48 is ready, I think we can just try it again.

**Comment by vanitasvitae** [comment] 2021-01-20 00:02
Release should be available on maven central now or within the next hours.

**Comment by tomholub** [comment] 2021-01-20 15:21
Thank you - I'll have a look at the expirations

**Comment by IvanPizhenko** [comment] 2021-01-20 19:48
Thanks @vanitasvitae, it works now!

**Comment by wiktor-k** [comment] 2021-01-22 21:36
> PGPainless is currently creating signatures of type 0x13 as I expected key signatures to be too ciritcal to be "generic".

My 2 eurocents: I think maybe you took a guidance from GnuPG that by default uses 0x13 for self-signatures and 0x10 for signatures over other's people's User IDs (this can be customized). For the record GnuPG treats all signature types the same way (except for 0x11: Persona certification that is completely ignored).
