### ISSUE TITLE
Please implement a SOP frontend

### ISSUE THREAD

**Issue by teythoon** [pgpainless/pgpainless#29] opened 2020-11-26 09:55 UTC
SOP [0] is an interface specification for OpenPGP implementations.  One of the main use cases is plugging implementations into the OpenPGP Interoperability Test suite [1].  The test suite has been very successful in finding bugs in various implementations.  Please join the fun :)

0: https://gitlab.com/dkg/openpgp-stateless-cli
1: https://tests.sequoia-pgp.org/

**Comment by vanitasvitae** [comment] 2020-11-26 09:57
Hehe don't tell anyone but I already started a prototype ;)

**Comment by vanitasvitae** [comment] 2020-11-26 10:01
Duplicate of #26

**Closed as completed by vanitasvitae** 2020-11-26 10:01 UTC

**Comment by tomholub** [comment] 2021-02-15 15:52
@teythoon thank you for your work and these issues. Overall, the tests are extremely helpful :+1:  also thank you @vanitasvitae for implementing the interface.
